const s = [
    {
        title: "Python  for Beginners",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-for-beginners",
    },
    {
        title: "Python  for Intermediate",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python--for-intermediate",
    },
    {
        title: "Python  for Advanced",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python--for-advanced",
    },
    {
        title: "Python  for Experts",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python--for-experts",
    },
    {
        title: "Python Data Science ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-data-science-",
    },
    {
        title: "Python Web Development ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-web-development-",
    },
    {
        title: "Python Machine Learning ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-machine-learning-",
    },
    {
        title: "Python Network Programming ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-network-programming-",
    },
    {
        title: "Python GUI Programming ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-gui-programming-",
    },
    {
        title: "Python Game Development ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-game-development-",
    },
    {
        title: "Python Web Scraping ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-web-scraping-",
    },
    {
        title: "Python Regular Expressions ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-regular-expressions-",
    },
    {
        title: "Python Image Processing ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-image-processing-",
    },
    {
        title: "Python Web Frameworks ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-web-frameworks-",
    },
    {
        title: "Python Database Programming ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-database-programming-",
    },
    {
        title: "Python Data Visualization ",
        description: "Learn Python in 1 hour",
        image: "https://via.placeholder.com/350x200",
        link: "/python-data-visualization-",
    },
    {
        title: "JavaScript  for Beginners",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript--for-beginners",
    },
    {
        title: "JavaScript  for Intermediate",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript--for-intermediate",
    },
    {
        title: "JavaScript  for Advanced",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript--for-advanced",
    },
    {
        title: "JavaScript Object Oriented Programming ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript--for-experts",
    },
    {
        title: "JavaScript Data Science ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-data-science-",
    },
    {
        title: "JavaScript Web Development ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-web-development-",
    },
    {
        title: "JavaScript Network Programming ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-network-programming-",
    },
    {
        title: "JavaScript GUI Programming ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-gui-programming-",
    },
    {
        title: "JavaScript Game Development ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-game-development-",
    },
    {
        title: "JavaScript Web Scraping ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-web-scraping-",
    },
    {
        title: "JavaScript Regular Expressions ",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-regular-expressions-",
    },
    {
        title: "SQL  for Beginners",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql--for-beginners",
    },
    {
        title: "SQL  for Intermediate",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql--for-intermediate",
    },
    {
        title: "SQL  for Advanced",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql--for-advanced",
    },
    {
        title: "SQL  for Experts",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql--for-experts",
    },
    {
        title: "Kali Linux  for Beginners",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux--for-beginners",
    },
    {
        title: "Kali Linux  for Intermediate",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux--for-intermediate",
    },
    {
        title: "Kali Linux  for Advanced",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux--for-advanced",
    },
    {
        title: "Cryptography  for Beginners",

        description: "Learn Cryptography in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux--for-experts",
    },
    {
        title: "Kali Linux Web Penetration Testing ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-web-penetration-testing-",
    },
    {
        title: "Kali Linux Network Penetration Testing ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-network-penetration-testing-",
    },
    {
        title: "Kali Linux Wireless Penetration Testing ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-wireless-penetration-testing-",
    },
    {
        title: "Kali Linux Password Cracking ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-password-cracking-",
    },
    {
        title: "Kali Linux Forensics ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-forensics-",
    },
    {
        title: "Kali Linux Exploitation ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-exploitation-",
    },
    {
        title: "Kali Linux Reverse Engineering ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-reverse-engineering-",
    },
    {
        title: "Kali Linux Post Exploitation ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-post-exploitation-",

    },
    {
        title: "Kali Linux Mobile Penetration Testing ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-mobile-penetration-testing-",
    },
    {
        title: "Kali Linux IoT Penetration Testing ",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-iot-penetration-testing-",
    },
    {
        title: "How to Install Kali Linux",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux",
    },
    {
        title: "How to Install Kali Linux on VirtualBox",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-virtualbox",
    },
    {
        title: "How to Install Kali Linux on VMware",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-vmware",
    },
    {
        title: "How to Install Kali Linux on Windows 10",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-windows-10",
    },
    {
        title: "How to Install Kali Linux on Raspberry Pi",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-raspberry-pi",
    },
    {
        title: "How to Install Kali Linux on Android",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-android",
    },
    {
        title: "How to Install Kali Linux on Chromebook",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-chromebook",
    },
    {
        title: "How to Install Kali Linux on Mac",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-mac",
    },
    {
        title: "How to Install Kali Linux on USB",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-usb",
    },
    {
        title: "How to Install Kali Linux on Dual Boot",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/how-to-install-kali-linux-on-dual-boot",
    },
    {
        title: "HTML ",
        description: "Learn HTML in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
        link: "/html-",
    },
    {
        title: "CSS ",
        description: "Learn CSS in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
        link: "/css-",
    },
    {
        title: "React ",
        description: "Learn React in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
        link: "/react-",
    },
    {
        title: "JavaScript Exercises",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-exercises",
    },
    {
        title: "Python Exercises",
        description: "Learn Python in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
        link: "/python-exercises",
    },
    {
        title: "SQL Exercises",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql-exercises",
    },
    {
        title: "React Exercises",
        description: "Learn React in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
        link: "/react-exercises",
    },
    {
        title: "HTML Exercises",
        description: "Learn HTML in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
        link: "/html-exercises",
    },
    {
        title: "CSS Exercises",
        description: "Learn CSS in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
        link: "/css-exercises",
    },
    {
        title: "Kali Linux Exercises",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-exercises",
    },

    {
        title: "Python References",
        description: "Learn Python in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
        link: "/python-references",
    },
    {
        title: "SQL References",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql-references",
    },
    {
        title: "React References",
        description: "Learn React in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
        link: "/react-references",
    },
    {
        title: "HTML References",
        description: "Learn HTML in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
        link: "/html-references",
    },
    {
        title: "CSS References",
        description: "Learn CSS in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
        link: "/css-references",
    },
    {
        title: "Kali Linux References",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-references",
    },
    {
        title: "JavaScript References",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-references",
    },
    {
        title: "Python Cheat Sheet",
        description: "Learn Python in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
        link: "/python-cheat-sheet",
    },
    {
        title: "SQL Cheat Sheet",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql-cheat-sheet",
    },
    {
        title: "React Cheat Sheet",
        description: "Learn React in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
        link: "/react-cheat-sheet",
    },
    {
        title: "HTML Cheat Sheet",
        description: "Learn HTML in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
        link: "/html-cheat-sheet",
    },
    {
        title: "CSS Cheat Sheet",
        description: "Learn CSS in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
        link: "/css-cheat-sheet",
    },
    {
        title: "Kali Linux Cheat Sheet",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-cheat-sheet",
    },
    {
        title: "JavaScript Cheat Sheet",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-cheat-sheet",
    },
    {
        title: "Python Quiz",
        description: "Learn Python in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg",
        link: "/python-quiz",
    },
    {
        title: "SQL Quiz",
        description: "Learn SQL in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg",
        link: "/sql-quiz",
    },
    {
        title: "React Quiz",
        description: "Learn React in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
        link: "/react-quiz",
    },
    {
        title: "HTML Quiz",
        description: "Learn HTML in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
        link: "/html-quiz",
    },
    {
        title: "CSS Quiz",
        description: "Learn CSS in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg",
        link: "/css-quiz",
    },
    {
        title: "Kali Linux Quiz",
        description: "Learn Kali Linux in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/69/Kali_Linux_Logo.png",
        link: "/kali-linux-quiz",
    },
    {
        title: "JavaScript Quiz",
        description: "Learn JavaScript in 1 hour",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg",
        link: "/javascript-quiz",
    }
];

export default s;